/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultaPersonal.java
 *
 * Created on 19-oct-2012, 11:37:37
 */

package formularios;

import BD.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jesus
 */
public class ConsultaPersonal extends javax.swing.JFrame {

    /** Creates new form ConsultaPersonal */
    public ConsultaPersonal() {
        initComponents();
        Consulta.setModel(modeloLista);
        consultaHorario.setModel(modelo);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Consulta = new javax.swing.JList();
        btnConsultar = new javax.swing.JButton();
        btnVerHorario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        consultaHorario = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Personal Actualmente Registrado");

        Consulta.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Consulta);

        btnConsultar.setText("Consultar Trabajadores");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnVerHorario.setText("Ver horario de Trabajadores");
        btnVerHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHorarioActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(consultaHorario);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close.png"))); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jButton1)
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(btnVerHorario)
                .addGap(147, 147, 147))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(btnConsultar)
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerHorario)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
    Consulta();        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void ConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaMouseClicked
        // TODO add your handling code here:
        RegistroHorario form = new RegistroHorario();
        form.setVisible(true);
    }//GEN-LAST:event_ConsultaMouseClicked

    private void btnVerHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHorarioActionPerformed
        // TODO add your handling code here:
        ConsultaHorario();
    }//GEN-LAST:event_btnVerHorarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPersonal().setVisible(true);
            }
        });
    }
DefaultListModel modeloLista = new DefaultListModel();
DefaultListModel modelo = new DefaultListModel();

    ConexionBD con=new ConexionBD();
     public void Consulta() {
    try {
    //Establece los valores para la sentencia SQL

    Connection c=con.conectar();
    //Obtiene la plantilla correspondiente a la persona indicada
    PreparedStatement verificarStmt = c.prepareStatement("SELECT *FROM personal");
    ResultSet rs = verificarStmt.executeQuery();

    //Si se encuentra el nombre en la base de datos
    if (rs.next()){
    //Lee la plantilla de la base de datos

    do{

    String nombre= rs.getString("nombre");
    String apellido= rs.getString("appaterno");
    String clave= rs.getString("clave");
    String objPersonal =(""+nombre+" "+apellido+"     "+clave);
    modeloLista.addElement(objPersonal);

        }while(rs.next());
    } else {

    }
    } catch (SQLException e) {
    //Si ocurre un error lo indica en la consola
    System.err.println("Error al verificar los datos de la huella.");
    }finally{
       con.desconectar();
    }
   }





      public void ConsultaHorario() {
          String elunes,emartes,emiercoles,ejueves,eviernes,slunes,smartes,smiercoles,sjueves,sviernes;

    try {
    //Establece los valores para la sentencia SQL
    String clavet = JOptionPane.showInputDialog("ingresa la clave del trabajador");
    Connection c=con.conectar();
    //Obtiene la plantilla correspondiente a la persona indicada
    PreparedStatement verificarStmt = c.prepareStatement("SELECT *FROM horario WHERE clave_trabajador=?");
    verificarStmt.setString(1,clavet);
    ResultSet rs = verificarStmt.executeQuery();

    //Si se encuentra el nombre en la base de datos
    if (rs.next()){
    //Lee la plantilla de la base de datos
    elunes= rs.getString("elunes");
    emartes= rs.getString("emartes");
    emiercoles= rs.getString("emiercoles");
    ejueves= rs.getString("ejueves");
    eviernes= rs.getString("eviernes");
    slunes= rs.getString("slunes");
    smartes= rs.getString("smartes");
    smiercoles= rs.getString("smiercoles");
    sjueves= rs.getString("sjueves");
    sviernes= rs.getString("sviernes");

    String objPersonal =("                 Horario del trabajador con clave: "+clavet);
    modelo.addElement(objPersonal);
    objPersonal =("\n");
    modelo.addElement(objPersonal);

    objPersonal =("                Lunes    Martes    Miercoles    Jueves     Viernes");
    modelo.addElement(objPersonal);


    objPersonal =("Entrada  "+elunes+"      "+emartes+"        "+emiercoles+"          "+ejueves+"        "+eviernes);
    modelo.addElement(objPersonal);

    objPersonal =("Salida     "+slunes+"      "+smartes+"        "+smiercoles+"          "+sjueves+"        "+sviernes);
    modelo.addElement(objPersonal);
    } else {

    }
    } catch (SQLException e) {
    //Si ocurre un error lo indica en la consola
    System.err.println("Error al verificar los datos de la huella.");
    }finally{
       con.desconectar();
    }
   }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList Consulta;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnVerHorario;
    private javax.swing.JList consultaHorario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
