/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Reporte.java
 *
 * Created on 12-dic-2012, 16:52:29
 */

package formularios;

import BD.ConexionBD;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFRichTextString;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.util.Region;
/**
 *
 * @author jesus
 */
public class Reporte extends javax.swing.JFrame {

    /** Creates new form Reporte */
    public Reporte() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensajes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Write.png"))); // NOI18N
        jButton1.setText("Generar Reporte");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jButton1ItemStateChanged(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        btnCerrar.setText("Volver");
        btnCerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCerrarMouseMoved(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Generacion de reporte de personal");

        mensajes.setColumns(20);
        mensajes.setRows(5);
        jScrollPane1.setViewportView(mensajes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(133, 133, 133))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // consulta de la base de datos
        try {
            //Establece los valores para la sentencia SQL
            Connection c=con.conectar();
            PreparedStatement consultar = c.prepareStatement("SELECT clave_trabajador FROM historial group by clave_trabajador;");
            //consultar.setString(1,camp_clave.getText());
            HSSFWorkbook libro = new HSSFWorkbook();//creamos libro de exel
            ResultSet rs = consultar.executeQuery();
            if (rs.next()){//
                //creacion del reporte en exel
                int fil=1;
                int cel=0;
                do{
                    String clavet=rs.getString("clave_trabajador");
                    HSSFSheet hoja = libro.createSheet("Reporte de "+rs.getString("clave_trabajador"));//creamos una hoja
                    hoja.addMergedRegion(new Region(0, (short) 0, 0,(short) 1));
                    HSSFRow fila = hoja.createRow(0);//creamos la primera fila
                    HSSFCell celda = fila.createCell(0);//creamos una celda
                    HSSFRichTextString texto = new HSSFRichTextString("CENTRO DE BACHILLERATO AGROPECUARIO No 77");
                    celda.setCellValue(texto);
 
                    fila = hoja.createRow(fil);//creamos la primera fila
                    
                    celda = fila.createCell(0);//creamos una celda
                    texto = new HSSFRichTextString("FECHA");
                    celda.setCellValue(texto);
                    celda = fila.createCell(1);//creamos una celda
                    texto = new HSSFRichTextString("ESTADO");
                    celda.setCellValue(texto);

                    Connection conect=con.conectar();
                    try{
                        PreparedStatement consulta_fechas = conect.prepareStatement("SELECT fecha, estado FROM historial where clave_trabajador='"+clavet+"';");
                        ResultSet rs_fechas = consulta_fechas.executeQuery();
                        if (rs_fechas.next()){
                            do{
                                fil=fil+1;
                                fila = hoja.createRow(fil);//creamos la siguiente fila
                                // Luego creamos el objeto que


                                HSSFCellStyle estiloCelda = libro.createCellStyle();
                                String estado= rs_fechas.getString("estado");
                                if(estado.equals("Retardo")){
                                    estiloCelda.setFillForegroundColor((short)13);
                                    estiloCelda.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
                                }
                                if(estado.equals("Falta")){
                                    estiloCelda.setFillForegroundColor((short)10);
                                    estiloCelda.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
                                }




                                celda = fila.createCell(0);//creamos una
                                String clave= rs_fechas.getString("fecha");
                                texto = new HSSFRichTextString(clave);
                                celda.setCellStyle(estiloCelda);
                                celda.setCellValue(texto);

                                cel=cel+1;
                                celda = fila.createCell(1);//creamos una

                                texto = new HSSFRichTextString(estado);
                                celda.setCellStyle(estiloCelda);
                                celda.setCellValue(texto);

                            }while(rs_fechas.next());
                            fil=1;
                        }
                    }catch(Exception e){
                        //
                    }finally{
                        con.desconectar();
                    }
                }while(rs.next());
                try {
                    FileOutputStream elFichero = new FileOutputStream("C:/Users/jesus/Desktop/Reportes.xls");
                    libro.write(elFichero);
                    elFichero.close();
                    mensajes.setText("El archivo se ha generado en:\nC:/Users/jesus/Desktop/Reportes.xls");
                    
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                 mensajes.setText("No existe historial de ningun trabajador");
            }
        } catch (SQLException e) {
            //Si ocurre un error lo indica en la consola
            System.err.println("Error al verificar los datos del personal.");
        }finally{
            con.desconectar();
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_jButton1MouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jButton1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ItemStateChanged

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:
        jButton1.setToolTipText("Generar reporte");
    }//GEN-LAST:event_jButton1MouseMoved

    private void btnCerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseMoved
        // TODO add your handling code here:
        btnCerrar.setToolTipText("Volver al menu anterior");
    }//GEN-LAST:event_btnCerrarMouseMoved
ConexionBD con=new ConexionBD();
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea mensajes;
    // End of variables declaration//GEN-END:variables

}
